complete -f -c kubectx
complete -f -c kubectx -l cache-dir -d "show the current namespace"
complete -f -c kubectx -a "-c --current" -d "show the current namespace"
complete -f -c kubectx -l "-e --cache-expires-in" -d "show the current namespace"
complete -f -c kubectx -a "-f --no-cache" -d "do not use cache"
complete -f -c kubectx -a "-g --global" -d "set the context globally"
complete -f -c kubectx -a "-h --help" -d "show the help message"
complete -f -c kubectx -a "-i --interactive" -d "select context interactively"
complete -f -c kubectx -a "-l --list" -d "show all kubeconfig files"
complete -f -c kubectx -a "-p --path" -d "show the kubeconfig path variable"
complete -f -c kubectx -a "-n --namespace" -d "switch to the specified namespace"
complete -f -c kubectx -a "-s --show" -d "show the kubeconfig for a context"
complete -f -c kubectx -n "[ (count (commandline -opc | string replace -ar '\-{1,2}\S+' '' | string split -n ' ')) -le 1 ]" -a "(kubectx -l)"
